init-stage: disable CGROUP with SV_SYSTEM enabled and sysinit/shutdown

diff --git a/sv/.lib/sh/init-stage b/sv/.lib/sh/init-stage
--- a/sv/.lib/sh/init-stage
+++ b/sv/.lib/sh/init-stage
@@ -117,16 +117,20 @@ svc_tmpdir()
 	#
 	# Set up CGroup
 	#
-	if yesno ${SV_CGROUP:-YES}; then
-		rs devfs start &
-		rs sysfs start
+	if yesno ${SV_CGROUP:-YES} && [ -z "${SV_SYSTEM}" ]; then
+		if rs devfs start && rs sysfs start; then
 		cgroup_start_sys
 		case ${?} in
 			(0) SV_CGROUP=Yes;;
 			(*) SV_CGROUP=No ;;
 		esac
-		ENV_SVC SV_CGROUP
+		else
+		SV_CGROUP=FALSE
+		fi
+	else
+		SV_CGROUP=DISABLE
 	fi
+	ENV_SVC SV_CGROUP
 }
 
 kill_svscan()
@@ -195,6 +199,10 @@ if   [ "${1}" = "--svscan" ]; then
 	echo $$ >${pidfile}
 	${__SV_CMD__} ${SV_RUNDIR} ${SV_OPTS} &
 elif [ "${1}" = "--sysinit" ]; then
+	if [ -n "${SV_SYSTEM}" ]; then
+		error "invalid init-stage usage -- SV_SYSTEM='${SV_SYSTEM}'"
+		end 1; exit 1;
+	fi
 	early_console
 	svc_init
 	sv-stage --sysinit
@@ -232,6 +240,10 @@ elif [ "${1}" = "--shutdown" -o "${1}" = "--reboot" ]; then
 		(--reboot|--shutdown)  sv-stage ${ACTION};;
 		(*) ACTION=--shutdown; sv-stage ${ACTION};;
 	esac
+	if [ -n "${SV_SYSTEM}" ]; then
+		end 0; exit 0;
+	fi
+
 	#
 	# CGroup clean up
 	#
