tmpfiles: further clean up (removed too many level of redundency)

diff --git a/sv/.lib/sh/tmpfiles b/sv/.lib/sh/tmpfiles
--- a/sv/.lib/sh/tmpfiles
+++ b/sv/.lib/sh/tmpfiles
@@ -22,14 +22,14 @@
 SV_LIBDIR="${0%/sh/*}"
 CHECKPATH="${SV_LIBDIR}/bin/checkpath"
 NAME="${0##*/}"
+NULL=/dev/null
 
 _checkprefix()
 {
-	local prefix="${1}" arg
-	shift
-	for arg; do
-		case "${prefix}" in
-			${arg}*) return 0 ;;
+	local prefix
+	for prefix; do
+		case "${path}" in
+			(${prefix}*) return 0 ;;
 		esac
 	done
 	return 1
@@ -37,139 +37,111 @@ _checkprefix()
 
 _warninvalid()
 {
-	echo "${NAME}: invalid entry -- line: ${LINENUM}: file ${FILE}" >&2
+	echo "${NAME}: invalid line -- num: ${LINENUM}: file ${FILE}" >&2
 	ERROR=$((${ERROR}+1))
 }
 
 _relabel()
 {
-	local path
-	local paths="${1}" mode="${2}" uid="${3}" gid="${4}"
-
-	for path in ${paths}; do
-		if [ -e "${path}" ]; then
-			[ -x /sbin/restorecon ] && ${DRYRUN} /sbin/restorecon $CHOPTS "${path}"
-			${DRYRUN} chown $CHOPTS "${uid}" "${path}"
-			${DRYRUN} chgrp $CHOPTS "${gid}" "${path}"
-			${DRYRUN} chmod $CHOPTS "${mode}" "${path}"
-		fi
-	done
+	[ -x /sbin/restorecon ] && ${DRYRUN} /sbin/restorecon $CHOPTS ${path}
+	${DRYRUN} chown $CHOPTS "${uid}"  ${path}
+	${DRYRUN} chgrp $CHOPTS "${gid}"  ${path}
+	${DRYRUN} chmod $CHOPTS "${mode}" ${path}
 }
 
 _restorecon()
 {
-    local path="${1}"
     if [ -x /sbin/restorecon ]; then
-        ${DRYRUN} /sbin/restorecon -F "${path}"
+        ${DRYRUN} /sbin/restorecon -F ${path}
     fi
 }
 
 _b()
 {
 	# Create a block device node if it doesn't exist yet
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}" age="${5}" arg="${6}"
-	if [ ! -e "${path}" ]; then
-		${DRYRUN} mknod -m "${mode}" "${path}" b ${arg/:/ }
-		_restorecon "${path}"
-		${DRYRUN} chown "${uid}:${gid}" "${path}"
-	fi
+	[ -e ${path} ] && return
+	${DRYRUN} mknod -m "${mode}" ${path} b ${arg/:/ }
+	_restorecon ${path}
+	${DRYRUN} chown "${uid}:${gid}" ${path}
 }
 
 _c()
 {
 	# Create a character device node if it doesn't exist yet
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}" age="${5}" arg="${6}"
-	if [ ! -e "${path}" ]; then
-		${DRYRUN} mknod -m "${mode}" "${path}" c ${arg/:/ }
-		_restorecon "${path}"
-		${DRYRUN} chown "${uid}:${gid}" "${path}"
-	fi
+	[ -e ${path} ] && return
+	${DRYRUN} mknod -m "${mode}" ${path} c ${arg/:/ }
+	_restorecon ${path}
+	${DRYRUN} chown "${uid}:${gid}" ${path}
 }
 
 _C()
 {
 	# recursively copy a file or directory
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}" age="${5}" arg="${6}"
-	if [ ! -e "${path}" ]; then
-		${DRYRUN} cp -r "${arg}" "${path}"
-		_restorecon "${path}"
-		${DRYRUN} chown "${uid}" "${path}"
-		${DRYRUN} chgrp "${gid}" "${path}"
-		${DRYRUN} chmod "${mode}" "${path}"
-	fi
+	[ -e ${path} ] && return
+	${DRYRUN} cp -r "${arg}" ${path}
+	_restorecon
+	${DRYRUN} chown "${uid}" ${path}
+	${DRYRUN} chgrp "${gid}" ${path}
+	${DRYRUN} chmod "${mode}" ${path}
 }
 
 _f()
 {
 	# Create a file if it doesn't exist yet
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}" age="${5}" arg="${6}"
-
 	${CREATE} || return 0
 
-	if [ ! -e "${path}" ]; then
-		${DRYRUN} ${CHECKPATH} -fq -m "${mode}" -o "${uid}:${gid}" "${path}"
-		[ -z "${arg}" ] || _w "${@}"
-	fi
+	[ -e ${path} ] && return
+	${DRYRUN} ${CHECKPATH} -fq -m "${mode}" -o "${uid}:${gid}" ${path}
+	[ -z "${arg}" ] || _w
 }
 
 _F()
 {
 	# Create or truncate a file
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}" age="${5}" arg="${6}"
-
 	${CREATE} || return 0
 
-	${DRYRUN} ${CHECKPATH} -Fq -m "${mode}" -o "${uid}:${gid}" "${path}"
-	[ -z "${arg}" ] || _w "${@}"
+	${DRYRUN} ${CHECKPATH} -Fq -m "${mode}" -o "${uid}:${gid}" ${path}
+	[ -z "${arg}" ] || _w
 }
 
 _d()
 {
 	# Create a directory if it doesn't exist yet
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}"
-
 	${CREATE} || return 0
 
-	if [ ! -d "${path}" ]; then
-		${DRYRUN} mkdir -p "${path}" 2>/dev/null
-		${DRYRUN} ${CHECKPATH} -dq -m "${mode}" -o "${uid}:${gid}" "${path}"
-	fi
+	[ -d ${path} ] && return
+	${DRYRUN} mkdir -p -m "${mode}" ${path} 2>${NULL}
+	${DRYRUN} ${CHECKPATH} -dq -m "${mode}" -o "${uid}:${gid}" ${path}
 }
 
 _D()
 {
 	# Create or empty a directory
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}"
-
-	if [ -d "${path}" ] && ${REMOVE}; then
-		${DRYRUN} find "${path}" -mindepth 1 -maxdepth 1 -xdev -exec rm -rf {} +
-		_restorecon "${path}"
+	if [ -d ${path} ] && ${REMOVE}; then
+		${DRYRUN} find ${path} -mindepth 1 -maxdepth 1 -xdev -exec rm -rf {} +
+		_restorecon
 	fi
 
 	if ${CREATE}; then
-		${DRYRUN} mkdir -p "${path}" 2>/dev/null
-		${DRYRUN} ${CHECKPATH} -Dq -m "${mode}" -o "${uid}:${gid}" "${path}"
+		${DRYRUN} mkdir -p -m "${mode}" ${path} 2>${NULL}
+		${DRYRUN} ${CHECKPATH} -Dq -m "${mode}" -o "${uid}:${gid}" ${path}
 	fi
 }
 
 _L()
 {
 	# Create a symlink if it doesn't exist yet
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}" age="${5}" arg="${6}"
-	[ ! -e "${path}" ] && ${DRYRUN} ln -s "${arg}" "${path}"
-	_restorecon "${path}"
+	[ ! -e ${path} ] && ${DRYRUN} ln -s "${arg}" ${path}
+	_restorecon
 }
 
 _p()
 {
 	# Create a named pipe (FIFO) if it doesn't exist yet
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}"
-
 	${CREATE} || return 0
 
-	if [ ! -p "${path}" ]; then
-		${DRYRUN} ${CHECKPATH} -Pq -m ${mode} -o "${uid}:${gid}" "${path}"
-	fi
+	[ -p ${path} ] && return
+	${DRYRUN} ${CHECKPATH} -Pq -m ${mode} -o "${uid}:${gid}" ${path}
 }
 
 _x()
@@ -198,16 +170,15 @@ _r()
 	# Remove a file or directory if it exists. This may not be used to remove
 	# non-empty directories, use R for that. Lines of this type accept shell-style
 	# globs in place of normal path names.
-	local path
-	local paths="${1}"
+	local p
 
 	${REMOVE} || return 0
 
-	for path in ${paths}; do
-		if [ -f ${path} ]; then
-			${DRYRUN} rm -f ${path}
-		elif [ -d ${path} ]; then
-			${DRYRUN} rmdir ${path}
+	for p in ${path}; do
+		if [ -f ${p} ]; then
+			${DRYRUN} rm -f ${p}
+		elif [ -d ${p} ]; then
+			${DRYRUN} rmdir ${p}
 		fi
 	done
 }
@@ -216,25 +187,19 @@ _R()
 {
 	# Recursively remove a path and all its subdirectories (if it is a directory).
 	# Lines of this type accept shell-style globs in place of normal path names.
-	local path
-	local paths="${1}"
-
 	${REMOVE} || return 0
 
-	for path in ${paths}; do
-		[ -d ${path} ] && ${DRYRUN} rm -rf --one-file-system ${path}
-	done
+	${DRYRUN} rm -rf --one-file-system ${path}
 }
 
 _w()
 {
 	# Write the argument parameter to a file, if it exists.
-	local path="${1}" mode="${2}" uid="${3}" gid="${4}" age="${5}" arg="${6}"
-	if [ -f "${path}" ]; then
+	if [ -f ${path} ]; then
 		if [ -n "${DRYRUN}" ]; then
 			echo "echo \"${arg}\" >>${path}"
 		else
-			echo "${arg}" >>"${path}"
+			echo "${arg}" >>${path}
 		fi
 	fi
 }
@@ -246,7 +211,7 @@ _z()
 	# place of normal path names.
 	${CREATE} || return 0
 
-	_relabel "${@}"
+	_relabel
 }
 
 _Z()
@@ -256,7 +221,7 @@ _Z()
 	# accept shell-style globs in place of normal path names.
 	${CREATE} || return 0
 
-	CHOPTS=-R _relabel "${@}"
+	CHOPTS=-R _relabel
 }
 
 help_message()
@@ -267,10 +232,10 @@ help_message()
 
 BOOT=false CREATE=false REMOVE=false CLEAN=false VERBOSE=false LINENO=false
 EXCLUDE= PREFIX= FILE= DRYRUN=
-fragments=
 # XXX: The harcoding of /usr/lib/ is an explicit choice by upstream
 tmpfiles_dirs='/usr/lib/tmpfiles.d/ /run/tmpfiles.d/ /etc/tmpfiles.d/'
-tmpfiles_basenames= tmpfiles_d=
+tmpfiles_names= tmpfiles_d=
+
 # Build a list of sorted unique basenames
 # directories declared later in the tmpfiles_d array will override earlier
 # directories, on a per file basename basis.
@@ -281,12 +246,12 @@ for d in ${tmpfiles_dirs}; do
 		case "${f}" in
 			*/systemd.conf|*/systemd-*.conf) continue ;;
 		esac
-		[ -f "${f}" ] && tmpfiles_basenames="${tmpfiles_basenames}\n${f##*/}"
+		[ -f "${f}" ] && tmpfiles_names="${tmpfiles_names}\n${f##*/}"
 	done # for f in ${d}
 done # for d in ${tmpfiles_dirs}
-tmpfiles_basenames="$(printf "${tmpfiles_basenames}\n" | sort -u)"
+tmpfiles_names="$(printf "${tmpfiles_names}\n" | sort -u)"
 
-for b in ${tmpfiles_basenames}; do
+for b in ${tmpfiles_names}; do
 	real_f=
 	for d in ${tmpfiles_dirs}; do
 		f=${d}${b}
@@ -340,7 +305,7 @@ for FILE in ${tmpfiles_d}; do
 		FORCE=false
 
 		# Unless we have both command and path, skip this line.
-		[ -n "${path}" ] || continue
+		[ -n ${path} ] || continue
 		case "${cmd}" in
 			([#]*|'') continue ;;
 		esac
@@ -381,19 +346,18 @@ for FILE in ${tmpfiles_d}; do
 		case "${arg}" in
 			(-|'') arg= ;;
 		esac
-		set -- "${path}" "${mode}" "${uid}" "${gid}" "${age}" "${arg}"
 
-		[ -n "${EXCLUDE}" ] &&   _checkprefix ${path} ${EXCLUDE} && continue
-		[ -n "${PREFIX}"  ] && ! _checkprefix ${path} ${PREFIX}  && continue
+		[ -n "${EXCLUDE}" ] &&   _checkprefix ${EXCLUDE} && continue
+		[ -n "${PREFIX}"  ] && ! _checkprefix ${PREFIX}  && continue
 
 		if ${FORCE}; then
 			case "${cmd}" in
-				([pLcb]) [ -f "${path}" ] && ${DRYRUN} rm -f "${path}"
+				([pLcb]) [ -f ${path} ] && ${DRYRUN} rm -f "${path}"
 			esac
 		fi
 
-		${VERBOSE} && echo _${cmd} "${@}"
-		_${cmd} "${@}"
+		${VERBOSE} && echo ${cmd} "${path}" "${mode}" "${uid}" "${gid}" "${age}" "${arg}"
+		_${cmd}
 		case "${?}" in
 			(0) ;;
 			(*) [ -z "${DRYRUN}" ] && ERROR=$((${ERROR}+1)) ;;
