rs.d/{OPTIONS.,}zram: 0.22.0 version
Major refactorization; do not fail if kernel module is already
initialized; do not try to umount in initialization (more than risky!)

diff --git a/rs.d/zram b/rs.d/zram
--- a/rs.d/zram
+++ b/rs.d/zram
@@ -3,7 +3,7 @@
 # $Header: /etc/rs.d/zram                                Exp $
 # $Author: (c) 2012-2015 -tclover <tokiclover@gmail.com> Exp $
 # $License: 2-clause/new/simplified BSD                  Exp $
-# $Version: 0.20.0 2015/04/18 12:33:03                   Exp $
+# $Version: 0.22.0 2015/04/18 12:33:03                   Exp $
 #
 
 description="Set up & initialize ZRAM devices"
@@ -13,19 +13,35 @@ SVC_BEFORE=bootmisc
 SVC_COMMANDS=reset
 
 :	${ZRAM_DEV:=4}
-:	${CONTINUE='{ num=$((${num}+1)); continue; }'}
 
 start()
 {
-	local dev fs mode dir num opt ret; num=0
+	local DEV dev fs mode dir num=0 offset=0 opt ret
+	local CONTINUE='{ num=$((${num}+1)); continue; }'
 
 	while true; do
-		dev=/dev/zram${num}
+		#
+		# Find the first free device
+		#
+		dev=/dev/zram$((${num}+${offset}))
 		[ -b ${dev} ] || break
+		if [ "$(cat /sys/block/zram${offset}/size)" != 0 ]; then
+			offset=$((${offset}+1)); continue;
+		fi
 		eval set -- \${ZRAM_DEV_${num}}
-		fs="${2}" dir="${3}" opt="${4}" mode="${5}"
+		size="${1}" fs="${2}" dir="${3}" opt="${4}" mode="${5}"
+		#
+		# Initialize device if defined
+		#
+		DEV="/sys/block/${dev##*/}"
+		[ -n "${size}" ] || break
+		[ -n "${ZRAM_COMP}"   ] && echo ${ZRAM_COMP}   >${DEV}/comp_algorithm
+		[ -n "${ZRAM_STREAM}" ] && echo ${ZRAM_STREAM} >${DEV}/max_comp_streams
+		echo ${size} >${DEV}/disksize
+		#
+		# Setup device if requested
+		#
 		[ -n "${fs}" ] || eval ${CONTINUE}
-		
 		case "${fs}" in
 			(swap)
 			begin "Activating ${dev} swap device"
@@ -53,62 +69,42 @@ start()
 
 start_pre()
 {
-	local dev num size
-	yesno ${ZRAM_INIT} || return 0
-
-	if grep -q zram /proc/modules; then
-		if ! rmmod zram >${NULL} 2>&1; then
-			reset && rmmod zram >${NULL} 2>&1
-		fi
-	fi
-	modprobe zram num_devices=${ZRAM_DEV} >${NULL} 2>&1 || reset
-
 	case "${ZRAM_COMP}" in
 		(lz4|lzo)     ;;
 		(*) ZRAM_COMP=;;
 	esac
-	dev=/sys/block/zram0 num=0
-	[ -w ${dev}/comp_algorithm    ] || ZRAM_COMP=
-	[ -w ${dev}//max_comp_streams ] || ZRAM_STREAM=
+	[ -w /sys/block/zram0/comp_algorithm   ] || ZRAM_COMP=
+	[ -w /sys/block/zram0/max_comp_streams ] || ZRAM_STREAM=
 
-	while true; do
-		dev=/sys/block/zram$num
-		[ -d ${dev} ] || break
-		eval set -- \${ZRAM_DEV_${num}}
-		size=${1}; [ -n "${size}" ] || eval ${CONTINUE}
-
-		[ -n "${ZRAM_COMP}"   ] && echo ${ZRAM_COMP}   >${dev}/comp_algorithm
-		[ -n "${ZRAM_STREAM}" ] && echo ${ZRAM_STREAM} >${dev}/max_comp_streams
-		echo ${size} >${dev}/disksize
-		eval ${CONTINUE}
-	done
+	if grep -qw zram /proc/modules; then
+		if ! rmmod zram >${NULL} 2>&1; then
+			reset && rmmod zram >${NULL} 2>&1 ||
+				{ warn "Cannot initialize kernel module"; return; }
+		fi
+	fi
+	modprobe zram num_devices=${ZRAM_DEV} >${NULL} 2>&1 || reset
 }
 
 stop()
 {
-	local dev fs dir num; num=0
+	local dev fs dir num=0
 	while true; do
-		dev=/dev/zram${num}
-		[ -b ${dev} ] || break
-		eval set -- \${ZRAM_DEV_${num}}
 		fs="${2}" dir="${3}"
-		[ -n "${fs}" ] || eval ${CONTINUE}
-
 		case "${fs}" in
-			(swap)
-			begin "De-Activating ${dev} swap device"
-			swapoff "${dev}" >${NULL} 2>&1
-			end ${?};;
-			(*)
-		case "${dir}" in
-			(*/run|*/tmp) ;;
-			(*)
-			begin "Unmounting ${dir}"
-			umount -l "${dir}" >${NULL} 2>&1
-			end ${?};;
-		esac;;
+			(swap) ;;
+			([a-z]*)
+			case "${dir}" in
+				(*/run|*/tmp) ;;
+				(*)
+				if grep -qw /proc/mounts; then
+					begin "Unmounting ${dir}"
+					umount -l "${dir}" >${NULL} 2>&1
+					end ${?}
+				fi;;
+			esac;;
+			(*) break;;
 		esac
-		eval ${CONTINUE}
+		num=$((${num}+1)); continue;
 	done
 	return 0
 }
@@ -130,7 +126,7 @@ reset()
 			ret=$((${ret}+1))
 			continue;;
 		esac
-		echo 1 >/sys/block/${dev#/dev}reset
+		echo 1 >/sys/block/${dev##*/}/reset
 	done
 	return ${ret}
 }
