runscript-functions typo fix

diff --git a/lib/sh/cmd b/lib/sh/cmd
--- a/lib/sh/cmd
+++ b/lib/sh/cmd
@@ -42,7 +42,7 @@ readonly SV_TYPE=sv
 SV_LIBDIR=${SVC_DIR}/../../lib
 
 if ! . ${SV_LIBDIR}/sh/runscript-functions; then
-	echo "${__cmd__}: error: Required file not found \`${SV_LIBDIR}/sh/run-functions'" >&2
+	echo "${__cmd__}: error: Required file not found \`${SV_LIBDIR}/sh/runscript-functions'" >&2
 	exit 1
 fi
 :	${SVC_CMD:=${SVC_NAME}}
diff --git a/lib/sh/depgen b/lib/sh/depgen
--- a/lib/sh/depgen
+++ b/lib/sh/depgen
@@ -22,7 +22,7 @@ name="${0##*/}"
 SV_LIBDIR="${0%/sh/*}"
 export LC_ALL=C LANG=C
 if ! . ${SV_LIBDIR}/sh/runscript-functions; then
-	echo "${name}: error: Required file not found \`${SV_LIBDIR}/sh/run-functions'" >&2
+	echo "${name}: error: Required file not found \`${SV_LIBDIR}/sh/runscript-functions'" >&2
 	exit 1
 fi
 SV_DEPDIR="${SV_TMPDIR}/deps"
diff --git a/lib/sh/init-stage b/lib/sh/init-stage
--- a/lib/sh/init-stage
+++ b/lib/sh/init-stage
@@ -51,7 +51,7 @@ else
 :	${SV_LIBDIR:=/lib/sv}
 fi
 if ! . ${SV_LIBDIR}/sh/runscript-functions; then
-	echo "${name}: error: Required file not found \`${SV_LIBDIR}/sh/run-functions'" >&2
+	echo "${name}: error: Required file not found \`${SV_LIBDIR}/sh/runscript-functions'" >&2
 	[ -n "${SV_OPTS}" ] && svc_rsh || exit 1
 fi
 :	${SV_SVCDIR:=/etc/sv}
diff --git a/lib/sh/runscript b/lib/sh/runscript
--- a/lib/sh/runscript
+++ b/lib/sh/runscript
@@ -69,7 +69,7 @@ shift
 readonly SVC_NAME SV_TYPE
 
 if ! . ${SV_LIBDIR}/sh/runscript-functions; then
-	echo "${0##*/}: error: Required file not found \`${SV_LIBDIR}/sh/run-functions'" >&2
+	echo "${0##*/}: error: Required file not found \`${SV_LIBDIR}/sh/runscript-functions'" >&2
 	exit 1
 fi
 
