cmd: minor error message formating

diff --git a/lib/sh/cmd b/lib/sh/cmd
--- a/lib/sh/cmd
+++ b/lib/sh/cmd
@@ -44,7 +44,7 @@ SV_LIBDIR=${SVC_DIR}/../../lib
 
 trap "rm -f ${SV_TMPDIR}/envs/${SVC_NAME}" EXIT INT TERM QUIT
 source "${SV_LIBDIR}"/sh/runscript-functions ||
-	{ echo "Required file not found." >&2; exit 1; }
+	{ echo "${__cmd__}: error: Required file not found." >&2; exit 1; }
 
 
 if [ "${__cmd__}" = "run" -o "${__cmd__}" = "finish" ]; then
