functions: added a new variable for pretty printing

diff --git a/lib/sh/functions b/lib/sh/functions
--- a/lib/sh/functions
+++ b/lib/sh/functions
@@ -1,11 +1,12 @@
 #
-# $Id:  @(#) shfunctions    2.1 2018/07/16 21:09:26                   Exp $
+# $Id:  @(#) shfunctions    2.1 2018/07/26 21:09:26                   Exp $
 # $C$:  Copyright (c) 2015-2018 tokiclover <tokiclover@gmail.com>     Exp $
 # $L$:  2-clause/new/simplified BSD License                           Exp $
 #
 
 if [ -z "${__FUNCTIONS__}" ]; then
 __FUNCTIONS__=1
+__eol_print__="\n"
 
 :	${NULL:=/dev/null}
 [ -x /usr/bin/logger ] && __SVC_LOGGER__=true || __SVC_LOGGER__=false
@@ -40,7 +41,7 @@ error()
 	fi
 	__print_len__=$((${#name}+3+${#message}))
 	local prefix="${name:+${color_fg_mag}${name}:${color_rst}}"
-	printf "${__print_eol__}${color_fg_red}error: ${prefix} ${@}\n" >&2
+	printf "${__print_eol__}${color_fg_red}error: ${prefix} ${message}${__eol_print__}" >&2
 }
 
 #
@@ -58,11 +59,11 @@ info()
 {
 	local message="${*}"
 	if yesno ${SVC_SYSLOG_INFO}; then
-		logger "${name}: info: ${@}"
+		logger "${name}: info: ${message}"
 	fi
 	__print_len__=$((${#name}+3+${#message}))
 	local prefix="${name:+${color_fg_ylw}${name}:${color_rst}}"
-	printf "${__print_eol__}${color_fg_blu}info: ${prefix} ${@}\n"
+	printf "${__print_eol__}${color_fg_blu}info: ${prefix} ${message}${__eol_print__}"
 }
 
 #
@@ -72,11 +73,11 @@ warn()
 {
 	local message="${*}"
 	if yesno ${SVC_SYSLOG}; then
-		logger "${name}: warning: ${@}"
+		logger "${name}: warning: ${message}"
 	fi
 	__print_len__=$((${#name}+3+${#message}))
 	local prefix="${name:+${color_fg_red}${name}:${color_rst}}"
-	printf "${__print_eol__}${color_fg_ylw}warning: ${prefix} ${@}\n" >&2
+	printf "${__print_eol__}${color_fg_ylw}warning: ${prefix} ${message}${__eol_print__}" >&2
 }
 
 #
@@ -84,15 +85,16 @@ warn()
 #
 begin()
 {
+	local message="${*}"
 	if yesno ${SVC_SYSLOG_INFO}; then
-		logger "${name}: notice: ${@}"
+		logger "${name}: notice: ${message}"
 	fi
 	printf "${__print_eol__}"
+	__eol_print__=
 	__print_eol__="\n"
-	local message="${*}"
 	__print_len__=$((${#name}*2+6+${#message}))
 	local prefix="${name:+${color_fg_mag}[${color_fg_blu}${name}${color_fg_mag}]${color_rst}}"
-	printf "${prefix} ${@}"
+	printf "${prefix} ${message}"
 }
 
 #
@@ -102,15 +104,17 @@ end()
 {
 	local suffix ret="${1:-0}"
 	shift
+	local message="${*}"
 	if yesno ${SVC_SYSLOG_INFO}; then
-		logger "${name}: notice: ${@}"
+		logger "${name}: notice: ${message}"
 	fi
 	case "${ret}" in
 		(0) suffix="${color_fg_blu}(${name}) [${color_fg_grn}ok${color_fg_blu}]${color_rst}";;
 		(*) suffix="${color_fg_ylw}(${name}) [${color_fg_red}no${color_fg_ylw}]${color_rst}";;
 	esac
 	__print_len__=$((${COLUMNS}-${__print_len__}))
-	printf "%*b\n" "${__print_len__}" "${@} ${suffix}"
+	printf "%*b\n" "${__print_len__}" "${message} ${suffix}"
+	__eol_print__="\n"
 	__print_eol__=
 	__print_len__=0
 	return "${ret}"
