functions: use lower case {ERROR,WARN} for error printing

diff --git a/lib/sh/functions b/lib/sh/functions
--- a/lib/sh/functions
+++ b/lib/sh/functions
@@ -1,5 +1,5 @@
 #
-# $Id:  @(#) shfunctions    2.0 2017/01/14 21:09:26                   Exp $
+# $Id:  @(#) shfunctions    2.0 2018/07/14 21:09:26                   Exp $
 # $C$:  Copyright (c) 2015-2018 tokiclover <tokiclover@gmail.com>     Exp $
 # $L$:  2-clause/new/simplified BSD License                           Exp $
 #
@@ -26,7 +26,7 @@ error()
 	local message="${*}"
 	__print_len__=$((${#name}+3+${#message}))
 	local prefix="${name:+${color_fg_mag}${name}:${color_rst}}"
-	printf "${__print_eol__}${color_fg_red}ERROR: ${prefix} ${@}\n" >&2
+	printf "${__print_eol__}${color_fg_red}error: ${prefix} ${@}\n" >&2
 }
 
 #
@@ -62,7 +62,7 @@ warn()
 	local message="${*}"
 	__print_len__=$((${#name}+3+${#message}))
 	local prefix="${name:+${color_fg_red}${name}:${color_rst}}"
-	printf "${__print_eol__}${color_fg_ylw}WARN: ${prefix} ${@}\n"
+	printf "${__print_eol__}${color_fg_ylw}warning: ${prefix} ${@}\n"
 }
 
 #
