init-stage: use a more cleaner runscript-functions handler

diff --git a/lib/sh/init-stage b/lib/sh/init-stage
--- a/lib/sh/init-stage
+++ b/lib/sh/init-stage
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id:  @(#) init-stage    1.8 2018/07/18 21:09:26                    Exp $
+# $Id:  @(#) init-stage    1.8 2018/07/22 21:09:26                    Exp $
 # $C$:  Copyright (c) 2015-2018 tokiclover <tokiclover@gmail.com>     Exp $
 # $L$:  2-clause/new/simplified BSD License                           Exp $
 #
@@ -51,7 +51,7 @@ else
 :	${SV_LIBDIR:=/lib/sv}
 fi
 if ! . ${SV_LIBDIR}/sh/runscript-functions; then
-	echo "Required file not found." >&2
+	echo "${name}: error: Required file not found \`${SV_LIBDIR}/sh/run-functions'" >&2
 	[ -n "${SV_OPTS}" ] && svc_rsh || exit 1
 fi
 :	${SV_SVCDIR:=/etc/sv}
