{rs,sv}-functions: svc_depend: Return proper value per type dependency

diff --git a/sv/.opt/supervision-functions b/sv/.opt/supervision-functions
--- a/sv/.opt/supervision-functions
+++ b/sv/.opt/supervision-functions
@@ -197,9 +197,15 @@ svc_depend()
 {
 	local dep
 	for dep in ${2-use:USE need:NEED before:BEFORE after:AFTER}; do
-		eval [ -n \"\${SVC_${dep#*:}}\" ] && command -v svc_${dep%:*} \
-			>${NULL} 2>&1 && svc_${dep%:*} ${1}
+		eval [ -n \"\${SVC_${dep#*:}}\" ] &&
+		command -v svc_${dep%:*} >${NULL} 2>&1 || continue
+		eval svc_${dep%:*} ${1}
+		eval RET_${dep#*:}=${?}
 	done
+	case ${RET_NEED:-0} in
+		(0) echo $$ >${SVC_PID}  ;;
+		(*) return ${RET_NEED:-0};;
+	esac
 }
 
 svc_after()
@@ -216,8 +222,11 @@ svc_after()
 
 svc_need()
 {
+	local val
 	if ! svc_use ${1-start} "${2-${SVC_NEED}}"; then
-		die "Failed to set up service dependencies."
+		val=${?}
+		error "Failed to set up service dependencies."
+		return ${val}
 	fi
 }
 svc_use()
@@ -356,7 +365,7 @@ svc_run()
 	if command -v svc_pre >${NULL} 2>&1; then
 		svc_pre
 	fi
-	svc_depend
+	svc_depend || return
 	eval exec ${ENV_CMD} ${ENV_OPTS} ${PRE_CMD} ${PRE_OPTS} ${SVC_CMD:-${SVC_NAME}} ${SVC_OPTS}
 }
 
